# Main Colors
unrecognized_file: darkorange
recognized_file:   darkorange
executable_file:   darkorange
dir:               teal

# Link
dead_link: red
link:      webpurple

# special files
socket:    green
blockdev:  green
chardev:   green

# Access Modes
write:     moccasin
read:      moccasin
exec:      moccasin
no_access: moccasin

# Age
day_old:     mediumspringgreen
hour_old:    lime
no_modifier: seagreen

# File Size
file_large:  orange
file_medium: gold
file_small:  peachpuff

# Random
report: white
user:   moccasin
tree:   slategray
empty:  yellow
error:  red
normal: darkkhaki
inode: moccasin

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    forestgreen
