#! python3
# copy email snippet to the clipboard

# plan: 
# 1) paste the snippet directly onto the email draft
# 2) parse the job folder, analyse and auto-fill the content of the snippet

import sys, os, re
import pyperclip
from tkinter.filedialog import askdirectory
from pathlib import Path

if len(sys.argv) < 2:
    print('Usage: python3 ihs_email.py [job] - copy phrase')
    sys.exit()

jobDir = Path(askdirectory())
job = os.path.basename(jobDir)

if 'Images' in os.listdir(jobDir):
    imgNo = len(os.listdir(jobDir / 'Images'))
else:
    print('Missing: Images folder')
    sys.exit()

guides = ""

# cant do, need regex
if 'Post-production' in os.listdir(jobDir):
    guides += 'post-production guidelines'
elif 'Shoot Brief' in 

if 'ref' in os.listdir(jobDir):
    guides += 'and the reference images'

newText = "Hi,\n\nPlease note that %s is being uploaded to the server, including %s images along with the %s. Let me know if there is any question. Thanks!\n\n" % (job, imgNo, guides)
amendText = "Hi,\n\nPlease note that there are amendments required, which are being uploaded to the server under the folder %s, including %s images along with the feedback pdf. Let me know if there is any question. Thanks!\n\n" % (job, imgNo)
