#! python3
# copy email template to the clipboard

# version:
# 1.0.0: first stable release with auto-fill function

# plan: 
# 1) paste the draft directly onto the gmail
# 2) [done] parse the job folder, analyse and auto-fill the content of the draft

import sys, os
import pyperclip
from tkinter.filedialog import askdirectory
from pathlib import Path

jobDir = Path(askdirectory())
job = jobDir.name
imgDir = jobDir / 'Images'

if imgDir.is_dir(): #check if Images folder exists
    # check if the Images folder contains product subfolders
    # if os.listdir(imgDir)[1]
    imgNo = len(os.listdir(imgDir))
else:
    print('Missing: Images folder')
    sys.exit()

guidesList = []

if 'Post-production' in str(os.listdir(jobDir)):
    guidesList.append('post-production guideline')
elif 'Shoot Brief' in str(os.listdir(jobDir)):
    guidesList.append('shoot brief')

if 'Retouch Note' in str(os.listdir(jobDir)):
    guidesList.append('retouch note')

if 'ref' in str(os.listdir(jobDir)):
    # refNo = len(os.listdir(jobDir / 'ref'))
    guidesList.append('reference images')

guidesList[-1] = 'and ' + guidesList[-1]
guides = ', '.join(guidesList)

newJob = """Hi,\n\nPlease note that %s is being uploaded to the server, including %s images along with the %s. Let me know if there is any question. Thanks!\n\n""" % (job, imgNo, guides)

amendJob = """Hi,\n\nPlease note that there are amendments required, which are being uploaded to the server under the folder %s, including %s images along with the feedback pdf. Let me know if there is any question. Thanks!\n\n""" % (job, imgNo)

if 'amendment' in str(jobDir):
    pyperclip.copy(amendJob)
else:
    pyperclip.copy(newJob)
