#! /bin/zsh

# script for checking Ralph Lauren images
# version: 1.0.1
# 1.0.0: stable release
# 1.1.0: image with 1 missing character rename & mispell 'comp' rename
# 1.1.1: fix bad substitue & rename comp bug; update shotname array; auto open report
# created by Zeric Chan
#
# plan
# 1) check image spec
# 2) check filename with 1 character difference and rename them
# 3) consider insert

exec > /tmp/RL_check.log 2>&1

emulate -LR zsh
setopt xtrace
setopt extended_glob
setopt null_glob 

# array of correct file names
typeset -a RL_shotname=(
		    BagAngle BagFront BagBack BagDetail1 BagDetail2 BagDetail3 BagInterior BagReversible BagSide
		    ShoeAngle ShoeBack ShoeOverhead ShoeProfile ShoeDetail1
		    TABLETOP TT-DETAIL1 TT-DETAIL2 TT-DETAIL3 TT-DETAIL4
		    LAYDOWN LAYDOWNBACK SL-DETAIL1 SL-DETAIL2 SL-DETAIL3
		    BUST BUSTBACK
		   )

# 
if [[ -e $1 ]]; then
	local PARENT=$(pwd)
	cd $1

	local currentRL_image=($(print -l *.tif)) # files in current session
	local currentRL_product=($(print -l $currentRL_image | cut -d_ -f1 | uniq)) # products in current session
	mkdir rename
	local RL_rename=rename/
	print "RL_check Report\n\nno. of products: ${#currentRL_product}\nno. of images: ${#currentRL_image}\n\n\potential wrong filenames:\n" > rename/report && \
	       local RL_report=rename/report

	for img in $currentRL_image; do
		local img_product=$(print $img | cut -d_ -f1)
		local img_shot=$(print ${img:s/.tif//} | cut -d_ -f2)
		local img_comp=$(print ${img:s/.tif//} | cut -d_ -f3)
		
		# check comp
		if [[ ${img_comp} == "" ]]; then
			:
		elif [[ ${img_comp} == COMP[1-9] ]]; then #COMP
			:
		elif [[ ${(U)img_comp} == COMP[1-9] ]]; then #comp or Comp
			local img_comp=${(U)img_comp}
			mv "${img}" "${img_product}_${img_shot}_${img_comp}.tif"
		elif [[ ${img_comp} == *[1-9] ]]; then #wrong spelling but end with digit
			local img_comp="COMP${img_comp[-1]}"
			mv "${img}" "${img_product}_${img_product}_${img_comp}.tif"
		else 
			print ${img} >> $RL_report
			mv ${img} $RL_rename
			continue
		fi

		# check shot name
		if [[ $(print "${RL_shotname}" | grep -w "${img_shot}") ]]; then #total correct shot name without comp
			continue #break current $img for loop and continue to the next $img
		elif [[ $(print "${(L)RL_shotname}" | grep -w "${(L)img_shot}") ]]; then #correct name but different capital
			for cor_shot_name in $RL_shotname; do
				if [[ ${(L)cor_shot_name} == ${(L)img_shot} && ${img_comp} == "" ]]; then
					mv "${img}" "${img_product}_${cor_shot_name}.tif"
					break
				elif [[ ${(L)cor_shot_name} == ${(L)img_shot} && ${img_comp} != "" ]]; then
					mv "${img}" "${img_product}_${cor_shot_name}_${img_comp}.tif"
					break
				fi
			done
		else
			for cor_shot_name in $RL_shotname; do
				##### Can combin with sort #####
				for (( i=1; i<(( ${#cor_shot_name} + 1 )); i++ )); do 
					#rename file with missing 1 character
					#remove character in [subscript] and compare
					if [[ ${(L)cor_shot_name/${cor_shot_name[$i]}/} == ${(L)img_shot} && ${img_comp} == "" ]]; then
						mv "${img}" "${img_product}_${cor_shot_name}.tif"
						break
					elif [[ ${(L)cor_shot_name/${cor_shot_name[$i]}/} == ${(L)img_shot} && ${img_comp} != "" ]]; then
						mv "${img}" "${img_product}_${cor_shot_name}_${img_comp}.tif"
						break
					fi

					#rename image with character swap
					#j=$(( i + 1 ))
					#if [[ ${(L)cor_shot_name:(($i-1)):2} == ${(L)img_shot[$j]}${(L)img_shot[$i]} && ${img_comp} == "" ]]; then
						#mv "${img}" "${img_product}_${cor_shot_name}.tif"
				done
			done
			print "$img" >> $RL_report
			mv ${img} $RL_rename
		fi
	done
	open $RL_report
	cd $PARENT
else
	print " target directory is missing!!"
	exit 2
fi
