#! /bin/zsh

# script for checking Ralph Lauren images
# version: 1.0.1
# 1.0.0: stable release
# 1.0.1: image with 1 missing character rename & mispell 'comp' rename
# created by Zeric Chan
#
# plan
# 1) check image spec
# 2) check filename with 1 character difference and rename them
# 3) consider comp and insert

exec > /tmp/RL_check.log 2>&1

emulate -LR zsh
setopt xtrace
setopt extended_glob
setopt null_glob 

# array of correct file names
typeset -a RL_shotname=(
		    BagAngle BagFront BagBack BagDetail1 BagInterior BagReversible BagSide
		    ShoeAngle ShoeBack ShoeOverhead ShoeProfile ShoeDetail1
		    TABLETOP TT-DETAIL1 TT-DETAIL2 TT-DETAIL3 TT-DETAIL4
		    LAYDOWN LAYDOWNBACK SL-DETAIL1 SL-DETAIL2
		    BUST BUSTBACK
		   )

# 
if [[ -e $1 ]]; then
	local PARENT=$(pwd)
	cd $1

	local currentRL_image=($(print -l *.tif)) # files in current session
	local currentRL_product=($(print -l $currentRL_image | cut -d_ -f1 | uniq)) # products in current session
	print "RL_check Report\n\n\
	       no. of products: ${#currentRL_product}\n\
	       no. of images: ${#currentRL_image}\n\n\
	       potential wrong filenames:\n" > report && \
	       local RL_report=report
	mkdir rename
	RL_rename=rename/

	for img in $currentRL_image; do
		local img_product=$(print $img | cut -d_ -f1)
		local img_shot=$(print ${img:s/.tif//} | cut -d_ -f2)
		local img_comp=$(print ${img:s/.tif//} | cut -d_ -f3)
		
		# check comp
		if [[ ${img_comp} == COMP[1-9] ]]; then #COMP
			:
		elif [[ ${(U)img_comp} == COMP[1-9] ]]; then #comp or Comp
			local img_comp="${(U)img_comp}"
		elif [[ ${img_comp} == *[1-9] ]]; then #wrong spelling but end with digit
			local img_comp="COMP${img_comp[-1]}"
		else 
			print ${img} >> $RL_report
			mv ${img} $RL_rename
			continue
		fi

		# check shot name
		if [[ $(print "${RL_shotname}" | grep -w "${img_shot}") ]]; then #total correct shot name without comp
			continue #break current $img for loop and continue to the next $img
		elif [[ $(print "${(L)RL_shotname}" | grep -w "${(L)img_shot}") ]]; then #correct name but different capital
			for cor_shot_name in $RL_shotname; do
				if [[ ${(L)cor_shot_name} == ${(L)img_shot} && ${img_comp} == "" ]]; then
					mv "${img}" "${img_product}_${cor_shot_name}.tif"
					break
				elif [[ ${(L)cor_shot_name} == ${(L)img_shot} && ${img_comp} != "" ]]; then
					mv "${img}" "${img_product}_${cor_shot_name}_${img_comp}.tif"
					break
				fi
			done
		else
			for cor_shot_name in $RL_shotname; do
				#rename file with missing 1 character
				##### Can combin with sort #####
				for (( i=1; i<(( ${#cor_shot_name} + 1 )); i++ )); do 
					if [[ ${(L)cor_shot_name/${cor_shot_name[$i]/}} == ${(L)img_shot} && ${img_comp} == "" ]]; then
						mv "${img}" "${img_product}_${cor_shot_name}.tif"
						break
					elif [[ ${(L)cor_shot_name/${cor_shot_name[$i]/}} == ${(L)img_shot} && ${img_comp} != "" ]]; then
						mv "${img}" "${img_product}_${cor_shot_name}_${img_comp}.tif"
						break
					fi
				done
			done
			print "$img" >> $RL_report
			mv ${img} $RL_rename
		fi
	done
	cd $PARENT
else
	print " target directory is missing!!"
	exit 2
fi
